services:
  - type: web
    name: real-estate-ledia
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn property_advisors.wsgi:application
    autoDeploy: true
    postDeployCommand: python manage.py migrate
    envVars:
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "real-estate-ledia.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://real-estate-ledia.onrender.com"
      # Uncomment if you add a Render Postgres database below:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: realestate-db
      #     property: connectionString

# databases:
#   - name: realestate-db
#     plan: free
