# Generated by Django 4.2.11 on 2024-03-28 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('property_status', models.CharField(choices=[('FS', 'For Sale'), ('FR', 'For Rent')], max_length=2, verbose_name='Property status')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Bathrooms')),
                ('garage', models.PositiveIntegerField(default=0, verbose_name='Garage')),
                ('sqm', models.PositiveIntegerField(help_text='in SQM', verbose_name='Area')),
                ('Photo', models.ImageField(upload_to='Properties/')),
                ('views', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='property.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ('-pub_date',),
            },
        ),
    ]
