# Generated by Django 4.2.11 on 2024-03-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sqm',
            field=models.DecimalField(decimal_places=2, help_text='in SQM', max_digits=10, verbose_name='Area'),
        ),
    ]
