# Generated by Django 4.2.11 on 2024-03-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_sqm'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='scr_map',
            field=models.TextField(blank=True, verbose_name='Mapp'),
        ),
    ]
