# Generated by Django 4.2.11 on 2024-03-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_scr_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Photo',
            new_name='MainPhoto',
        ),
        migrations.AddField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='Properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='Properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='Properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='Properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='Properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='Properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='scr_map',
            field=models.TextField(blank=True, verbose_name='Map'),
        ),
    ]
